### ISSUE TITLE
Red warning of mismatching data and protocol does not go away after correcting the issue

### ISSUE THREAD

**Issue by HarrisNami** [neuropoly/qMRLab#222] opened 2018-05-22 17:49 UTC
When I load the data the warning pops up. I change the protocol to match the data but the warning does not update and is still there. I can still go through with the fitting and it works no problem, but still makes it confusing initially as to whether there is a problem or not. See screenshot.

![screen shot 2018-05-22 at 1 44 26 pm](https://user-images.githubusercontent.com/29234406/40380354-ddc4258e-5dc6-11e8-8930-a3bb05014160.png)

**Comment by HarrisNami** [comment] 2018-05-22 19:15
This is on the ROI branch, would that possibly make a difference @mathieuboudreau ? Should I retry this on master to see if it yields the same issue?

**Comment by mathieuboudreau** [comment] 2018-05-22 19:20
@HarrisNami it depends on when the last time master was merged into the ROI branch. You can check it on master if you want – if it is fixed in master (which in early April, some data-checking was pushed), then merging master to the roi branch might be the only fix needed. If it still happens in master, then I think @tanguyduval or @ileppe should be the ones looking into it (if they have the time), as they're the ones who developed the data-checking feature recently.

Did you double check to verify that the data was acquired with only 4 inversion points, and not 9 like it seems to be suggesting? @ileppe it's odd that the error is shown, but @HarrisNami can still fit. Do we want to prevent this?

**Comment by HarrisNami** [comment] 2018-05-22 20:55
Ok, I tried it on Master and still get the same issue.

**Comment by tanguyduval** [comment] 2018-05-22 21:31
Your protocol (table on the right) has 4 rows. The warning displays 9...
We need to check the checkinputs in abstract class...
Thanks for reporting Harris, I'll try to reproduce.

We really need to add a button "report bug" on the interface that would
send us all the variables and infos ! That would be so handy!


Le mar. 22 mai 2018 à 21:20, Mathieu Boudreau <notifications@github.com> a
écrit :

**Comment by HarrisNami** [comment] 2018-05-22 21:33
The warning displays 9 because of the initial "default" protocol that is loaded by qMRLab which for this case has 9 rows. So as soon as I load the data thats when the error appears because the data has 4 frames and the default protocol has 9 rows. Hope that clarifies a bit.

**Comment by mathieuboudreau** [comment] 2018-05-22 21:42
@HarrisNami Yup that's what I got out of your first message. That warning message is intentional, so the bug as I see it is the warning not disappearing after you've setup the protocol and reload the data, as you've described!

**Closed** 2018-10-18 10:15 UTC
Labels: interface, priority:medium
